version: "3"
services:
    node:
        build: .
        ports:
            - 3001:3001
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: Software12&
        volumes:
        - mysql-data:/var/lib/mysql 
        ports:
            - 3306:3306                 
volumes:
    mysql-data: {}